namespace MapleAPI.Enum;

public enum MaplePotentialOptionType
{
    IGNORE_ARMOR,
    ATTACK_RATE,
    MAGIC_RATE,
    BOSS_DAMAGE,
    DAMAGE,
    CRITICAL_CHANCE,
    ATTACK,
    MAGIC,
    STR_RATE,
    DEX_RATE,
    INT_RATE,
    LUK_RATE,
    ALL_STAT_RATE,
    MAX_HP_RATE,
    MAX_MP_RATE,
    STR,
    DEX,
    INT,
    LUK,
    LEVEL_STR,
    LEVEL_DEX,
    LEVEL_INT,
    LEVEL_LUK,
    ALL_STAT,
    MAX_HP,
    MAX_MP,
    COOLDOWN_DECREASE,
    CRITICAL_DAMAGE,
    ITEM_DROP,
    MESO_DROP,
    OTHER
}